version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:80"

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
